name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: windows-2019
    strategy:
      matrix:
        image: [ unityci/editor:windows-2022.2.6f1-windows-il2cpp-1, unityci/editor:windows-2020.3.22f1-windows-il2cpp-1, unityci/hub:windows-latest ]

    steps:
      - uses: actions/checkout@v3
      - run: docker pull ${{ matrix.image }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
#       - name: Release
#         uses: marvinpinto/action-automatic-releases@latest
#         with:
#           repo_token: "${{ secrets.GITHUB_TOKEN }}"
#           prerelease: ${{ github.ref_type != 'tag' }}
#           automatic_release_tag: ${{ github.ref_type != 'tag' && 'latest' || null }}
#           title: ${{ github.ref_type != 'tag' && format('Build {0}', github.run_number) || null }}
#           files: test
